[[Qt6Svg]]
arch = "aarch64"
git-tree-sha1 = "7feb499643ba8fc43eaf51d79c5d8f355453b965"
os = "macos"

    [[Qt6Svg.download]]
    sha256 = "a4543d72290850f2305f9d2a08d8489ae5853b4706c1cacd43142674c1ad9ef1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.aarch64-apple-darwin.tar.gz"
[[Qt6Svg]]
arch = "x86_64"
git-tree-sha1 = "e082c0a439864857fe6e0d8f1faa4d4614c4ac9d"
os = "macos"

    [[Qt6Svg.download]]
    sha256 = "f1cee92e25da34bce28d14a06969445005ce5b4865c28401bdc509b18873dcb2"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.x86_64-apple-darwin.tar.gz"
[[Qt6Svg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69466ca2e043454f5f80f204386d759dcad64afd"
os = "windows"

    [[Qt6Svg.download]]
    sha256 = "054abd56d7cd2820105ce995e0c4c240ddda1afd91068f27e927e18702388e9f"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt6Svg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c2c12493848aa1ae990e1289be34ddd517db9bb"
os = "windows"

    [[Qt6Svg.download]]
    sha256 = "012e44f06d00a4d3d7bbad7345ed9ed9b8d78eeb9200e88f26c7ef1d79b24e98"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt6Svg]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bdd0fddf8164b315ba3141539ed32d3a4a427c8"
libc = "glibc"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "a6157b5fd5b78dac44c52281c0d0d1dd9e1fcd697414c6e9e6387523b85099ac"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6Svg]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "722e0ea14794d95b06ae7860c651277e6e30dc60"
libc = "musl"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "9c3623a44c1fd946a4c837ad26d20ad0d4c45e4659bb2c743605611e0e7e177a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Svg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d89340d63a95773d2037e12e994294c4ee6f153e"
libc = "glibc"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "3f92e86994a8d0c3603863fe07ce7e2341178a5abe51bfd8ad4dc4d2e06c877d"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6Svg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6951c6b4ad13d9c3e0cf94665a288fe8a08a2176"
libc = "musl"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "a4431297614420c248e73f9e7b96f764d77f51beb61e356756a65f286aa6b630"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6Svg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3b021eb97f8e610210174df88dddbcde619f3a4"
libc = "glibc"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "ba5be2fcddd1fa8dfac9981b3266eaa62cf07d16cfad6e4cdcae02766bb9be19"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6Svg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5da5b487cb69fd4120f814b2fa554f85047e6a10"
libc = "musl"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "093dcb3c05d2109f15af04cfbb55e0cfb29da3db24cdb69dd71f2684efbc8419"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6Svg]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46f29c4e61efd0bb7f8bda2b2685c70ef9785ab8"
libc = "glibc"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "882962cb12116abac836246721a49f83eb2b6547b0103a155413205174b4efdb"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6Svg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7093a4e251a40ae59336472cb7c3d540b77916aa"
libc = "glibc"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "2ab3cbb35237c15e4e10ad350db84f0bf5728523252808a6a10512720c2b8d2c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6Svg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4391a6dfe1ddac7d8a578ac7fd4654d1fb79656"
libc = "musl"
os = "linux"

    [[Qt6Svg.download]]
    sha256 = "a2da6dff57498f8d9ca8473169bec6658cbb3fc056b11e240f9881478fa74a2a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6Svg]]
arch = "x86_64"
git-tree-sha1 = "d466c1380f784fdc6d2fa0eb393eb6ce913e2217"
os = "freebsd"

    [[Qt6Svg.download]]
    sha256 = "09dc18bffc824bfbf0f816a955b44243a072816c9ba31f2bde5ce6f310a3da78"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Svg_jll.jl/releases/download/Qt6Svg-v6.10.2+0/Qt6Svg.v6.10.2.x86_64-unknown-freebsd.tar.gz"
